In [ ]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("airline_2m.csv", encoding="ISO-8859-1")

C:\Users\zakar\AppData\Local\Temp\ipykernel_4948\2865389816.py:1: DtypeWarning: Columns (69,76,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("airline_2m.csv", encoding="ISO-8859-1")

In [4]:
df.columns

Index(['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate',
       'Reporting_Airline', 'DOT_ID_Reporting_Airline',
       'IATA_CODE_Reporting_Airline', 'Tail_Number',
       ...
       'Div4WheelsOff', 'Div4TailNum', 'Div5Airport', 'Div5AirportID',
       'Div5AirportSeqID', 'Div5WheelsOn', 'Div5TotalGTime',
       'Div5LongestGTime', 'Div5WheelsOff', 'Div5TailNum'],
      dtype='object', length=109)

## Cleaning and preprocessing (based on exploration data)

droping columns with all missing values

In [5]:
df = df.dropna(how='all', axis=1)

filling missing delay values with 0

In [6]:
for col in ['CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay']:
    if col in df.columns:
        df[col] = df[col].fillna(0)

fillinf missing categorical values with 'unknown'

In [7]:
for col in ['CancellationCode']:
    if col in df.columns:
        df[col] = df[col].fillna("unknown")

Converting FlightDate to datetime

In [8]:
df['FlightDate'] = pd.to_datetime(df['FlightDate'])

converting categorical columns to category type

In [9]:
categorical_cols = ['Reporting_Airline', 'IATA_CODE_Reporting_Airline', 'Origin', 'Dest', 'CancellationCode']
for col in categorical_cols:
    if col in df.columns:
        df[col] = df[col].astype('category')

standardizing column values (converting OriginState and DestState to uppercase values for consistency)

In [10]:
df['OriginState'] = df['OriginState'].str.upper()
df['DestState'] = df['DestState'].str.upper()

converting time columns from hhmm to "minutes since midnight"

In [11]:
def convert_to_minutes(time):
    if pd.isna(time) or time < 0:
        return np.nan
    time_str = str(int(time)).zfill(4)
    return int(time_str[:2]) * 60 + int (time_str[2:])

In [12]:
for col in ['CRSDepTime', 'DepTime', 'WheelsOff', 'WheelsOn', 'CRSArrTime', 'ArrTime']:
    if col in df.columns:
        df[col] = df[col].apply(convert_to_minutes)

column check after cleaning

In [13]:
df.columns

Index(['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate',
       'Reporting_Airline', 'DOT_ID_Reporting_Airline',
       'IATA_CODE_Reporting_Airline', 'Tail_Number',
       'Flight_Number_Reporting_Airline', 'OriginAirportID',
       'OriginAirportSeqID', 'OriginCityMarketID', 'Origin', 'OriginCityName',
       'OriginState', 'OriginStateFips', 'OriginStateName', 'OriginWac',
       'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID', 'Dest',
       'DestCityName', 'DestState', 'DestStateFips', 'DestStateName',
       'DestWac', 'CRSDepTime', 'DepTime', 'DepDelay', 'DepDelayMinutes',
       'DepDel15', 'DepartureDelayGroups', 'DepTimeBlk', 'TaxiOut',
       'WheelsOff', 'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrTime', 'ArrDelay',
       'ArrDelayMinutes', 'ArrDel15', 'ArrivalDelayGroups', 'ArrTimeBlk',
       'Cancelled', 'CancellationCode', 'Diverted', 'CRSElapsedTime',
       'ActualElapsedTime', 'AirTime', 'Flights', 'Distance', 'DistanceGroup',
       'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay',
       'LateAircraftDelay', 'FirstDepTime', 'TotalAddGTime', 'LongestAddGTime',
       'DivAirportLandings', 'DivReachedDest', 'DivActualElapsedTime',
       'DivArrDelay', 'DivDistance', 'Div1Airport', 'Div1AirportID',
       'Div1AirportSeqID', 'Div1WheelsOn', 'Div1TotalGTime',
       'Div1LongestGTime', 'Div1WheelsOff', 'Div1TailNum', 'Div2Airport',
       'Div2AirportID', 'Div2AirportSeqID', 'Div2WheelsOn', 'Div2TotalGTime',
       'Div2LongestGTime', 'Div2WheelsOff', 'Div2TailNum'],
      dtype='object')

In [18]:
pd.set_option('display.max_columns', None)
df

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Origin,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,Dest,DestCityName,DestState,DestStateFips,DestStateName,DestWac,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrTime,ArrDelay,ArrDelayMinutes,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,Cancelled,CancellationCode,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime,TotalAddGTime,LongestAddGTime,DivAirportLandings,DivReachedDest,DivActualElapsedTime,DivArrDelay,DivDistance,Div1Airport,Div1AirportID,Div1AirportSeqID,Div1WheelsOn,Div1TotalGTime,Div1LongestGTime,Div1WheelsOff,Div1TailNum,Div2Airport,Div2AirportID,Div2AirportSeqID,Div2WheelsOn,Div2TotalGTime,Div2LongestGTime,Div2WheelsOff,Div2TailNum
0,1998,1,1,2,5,1998-01-02,NW,19386,NW,N297US,675,13487,1348701,31650,MSP,"Minneapolis, MN",MN,27.0,Minnesota,63,14869,1486902,34614,SLC,"Salt Lake City, UT",UT,49.0,Utah,87,1000,1019.0,19.0,19.0,1.0,1.0,1600-1659,24.0,1043.0,1136.0,3.0,1116,1139.0,23.0,23.0,1.0,1.0,1800-1859,0.0,unknown,0.0,176.0,180.0,153.0,1.0,991.0,4,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2009,2,5,28,4,2009-05-28,FL,20437,FL,N946AT,671,13342,1334202,33342,MKE,"Milwaukee, WI",WI,55.0,Wisconsin,45,13204,1320401,31454,MCO,"Orlando, FL",FL,12.0,Florida,33,724,722.0,-2.0,0.0,0.0,-1.0,1200-1259,10.0,732.0,933.0,8.0,941,941.0,0.0,0.0,0.0,0.0,1500-1559,0.0,unknown,0.0,157.0,159.0,141.0,1.0,1066.0,5,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013,2,6,29,6,2013-06-29,MQ,20398,MQ,N665MQ,3297,11921,1192102,31921,GJT,"Grand Junction, CO",CO,8.0,Colorado,82,11298,1129803,30194,DFW,"Dallas/Fort Worth, TX",TX,48.0,Texas,74,990,1004.0,14.0,14.0,0.0,0.0,1600-1659,9.0,1013.0,1176.0,6.0,1185,1182.0,-3.0,0.0,0.0,-1.0,1900-1959,0.0,unknown,0.0,135.0,118.0,103.0,1.0,773.0,4,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,3,8,31,2,2010-08-31,DL,19790,DL,N6705Y,1806,12892,1289201,32575,LAX,"Los Angeles, CA",CA,6.0,California,91,11433,1143301,31295,DTW,"Detroit, MI",MI,26.0,Michigan,43,785,785.0,0.0,0.0,0.0,0.0,1300-1359,23.0,808.0,1208.0,7.0,1235,1215.0,-20.0,0.0,0.0,-2.0,2000-2059,0.0,unknown,0.0,270.0,250.0,220.0,1.0,1979.0,8,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2006,1,1,15,7,2006-01-15,US,20355,US,N504AU,465,11618,1161801,31703,EWR,"Newark, NJ",NJ,34.0,New Jersey,21,11057,1105702,31057,CLT,"Charlotte, NC",NC,37.0,North Carolina,36,1100,1151.0,51.0,51.0,1.0,3.0,1800-1859,19.0,1170.0,1250.0,8.0,1226,1258.0,32.0,32.0,1.0,2.0,2000-2059,0.0,unknown,0.0,126.0,107.0,80.0,1.0,529.0,3,0.0,0.0,0.0,0.0,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999995,2008,1,3,23,7,2008-03-23,WN,19393,WN,N712SW,966,12889,1288902,32211,LAS,"Las Vegas, NV",NV,32.0,Nevada,85,14107,1410701,30466,PHX,"Phoenix, AZ",AZ,4.0,Arizona,81,880,884.0,4.0,4.0,0.0,0.0,1400-1459,10.0,894.0,939.0,4.0,950,943.0,-7.0,0.0,0.0,-1.0,1500-1559,0.0,unknown,0.0,70.0,59.0,45.0,1.0,256.0,2,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999996,1999,1,1,5,2,1999-01-05,CO,19704,CO,N14308,529,11618,1161801,31703,EWR,"Newark, NJ",NJ,34.0,New Jersey,21,11298,1129802,30194,DFW,"Dallas/Fort Worth, TX",TX,48.0,Texas,74,585,585.0,0.0,0.0,0.0,0.0,0900-0959,30.0,615.0,748.0,6.0,762,754.0,-8.0,0.0,0.0,-1.0,1200-1259,0.0,unknown,0.0,237.0,229.0,193.0,1.0,1372.0,6,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999997,2003,4,11,14,5,2003-11-14,US,20355,US,N528AU,1457,10994,1099401,30994,CHS,"Charleston, SC",SC,45.0,South Carolina,37,11057,1105702,31057,CLT,"Charlotte, NC",NC,37.0,North Carolina,36,745,739.0,-6.0,0.0,0.0,-1.0,1200-1259,11.0,750.0,785.0,3.0,799,788.0,-11.0,0.0,0.0,-1.0,1300-1359,0.0,unknown,0.0,54.0,49.0,35.0,1.0,168.0,1,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999998,2012,2,5,15,2,2012-05-15,WN,19393,WN,N281WN,536,13232,1323202,30977,MDW,"Chicago, IL",IL,17.0,Illinois,41,10693,1069302,30693,BNA,"Nashville, TN",TN,47.0,Tennessee,54,1110,1118.0,8.0,8.0,0.0,0.0,1800-1859,8.0,1126.0,1182.0,5.0,1190,1187.0,-3.0,0.0,0.0,-1.0,1900-1959,0.0,unknown,0.0,80.0,69.0,56.0,1.0,395.0,2,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999999,2003,2,4,29,2,2003-04-29,UA,19977,UA,N364UA,1241,12264,1226401,30852,IAD,"Washington, DC",VA,51.0,Virginia,38,13930,1393001,30977,ORD,"Chicago, IL",IL,17.0,Illinois,41,975,970.0,-5.0,0.0,0.0,-1.0,1600-1659,15.0,985.0,1019.0,11.0,1044,1030.0,-14.0,0.0,0.0,-1.0,1700-1759,0.0,unknown,0.0,129.0,120.0,94.0,1.0,589.0,3,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Checking for instances with early arrivals or departures (negative delay values):

In [23]:
columns_to_check = ['DepDelay', 'ArrDelay']

# Filter rows where any of the specified columns have a value < 0
df_negative = df[(df[columns_to_check] < 0).any(axis=1)]
df_negative

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Origin,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,Dest,DestCityName,DestState,DestStateFips,DestStateName,DestWac,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrTime,ArrDelay,ArrDelayMinutes,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,Cancelled,CancellationCode,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime,TotalAddGTime,LongestAddGTime,DivAirportLandings,DivReachedDest,DivActualElapsedTime,DivArrDelay,DivDistance,Div1Airport,Div1AirportID,Div1AirportSeqID,Div1WheelsOn,Div1TotalGTime,Div1LongestGTime,Div1WheelsOff,Div1TailNum,Div2Airport,Div2AirportID,Div2AirportSeqID,Div2WheelsOn,Div2TotalGTime,Div2LongestGTime,Div2WheelsOff,Div2TailNum
1,2009,2,5,28,4,2009-05-28,FL,20437,FL,N946AT,671,13342,1334202,33342,MKE,"Milwaukee, WI",WI,55.0,Wisconsin,45,13204,1320401,31454,MCO,"Orlando, FL",FL,12.0,Florida,33,724,722.0,-2.0,0.0,0.0,-1.0,1200-1259,10.0,732.0,933.0,8.0,941,941.0,0.0,0.0,0.0,0.0,1500-1559,0.0,unknown,0.0,157.0,159.0,141.0,1.0,1066.0,5,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013,2,6,29,6,2013-06-29,MQ,20398,MQ,N665MQ,3297,11921,1192102,31921,GJT,"Grand Junction, CO",CO,8.0,Colorado,82,11298,1129803,30194,DFW,"Dallas/Fort Worth, TX",TX,48.0,Texas,74,990,1004.0,14.0,14.0,0.0,0.0,1600-1659,9.0,1013.0,1176.0,6.0,1185,1182.0,-3.0,0.0,0.0,-1.0,1900-1959,0.0,unknown,0.0,135.0,118.0,103.0,1.0,773.0,4,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,3,8,31,2,2010-08-31,DL,19790,DL,N6705Y,1806,12892,1289201,32575,LAX,"Los Angeles, CA",CA,6.0,California,91,11433,1143301,31295,DTW,"Detroit, MI",MI,26.0,Michigan,43,785,785.0,0.0,0.0,0.0,0.0,1300-1359,23.0,808.0,1208.0,7.0,1235,1215.0,-20.0,0.0,0.0,-2.0,2000-2059,0.0,unknown,0.0,270.0,250.0,220.0,1.0,1979.0,8,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2006,3,8,7,1,2006-08-07,CO,19704,CO,N27724,1431,10721,1072101,30721,BOS,"Boston, MA",MA,25.0,Massachusetts,13,11042,1104201,30647,CLE,"Cleveland, OH",OH,39.0,Ohio,44,1075,1071.0,-4.0,0.0,0.0,-1.0,1700-1759,33.0,1104.0,1198.0,4.0,1200,1202.0,2.0,2.0,0.0,0.0,2000-2059,0.0,unknown,0.0,125.0,131.0,94.0,1.0,563.0,3,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2014,2,4,3,4,2014-04-03,WN,19393,WN,N374SW,1463,11540,1154003,30615,ELP,"El Paso, TX",TX,48.0,Texas,74,11259,1125903,30194,DAL,"Dallas, TX",TX,48.0,Texas,74,625,625.0,0.0,0.0,0.0,0.0,1000-1059,10.0,635.0,772.0,3.0,780,775.0,-5.0,0.0,0.0,-1.0,1300-1359,0.0,unknown,0.0,95.0,90.0,77.0,1.0,562.0,3,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999995,2008,1,3,23,7,2008-03-23,WN,19393,WN,N712SW,966,12889,1288902,32211,LAS,"Las Vegas, NV",NV,32.0,Nevada,85,14107,1410701,30466,PHX,"Phoenix, AZ",AZ,4.0,Arizona,81,880,884.0,4.0,4.0,0.0,0.0,1400-1459,10.0,894.0,939.0,4.0,950,943.0,-7.0,0.0,0.0,-1.0,1500-1559,0.0,unknown,0.0,70.0,59.0,45.0,1.0,256.0,2,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999996,1999,1,1,5,2,1999-01-05,CO,19704,CO,N14308,529,11618,1161801,31703,EWR,"Newark, NJ",NJ,34.0,New Jersey,21,11298,1129802,30194,DFW,"Dallas/Fort Worth, TX",TX,48.0,Texas,74,585,585.0,0.0,0.0,0.0,0.0,0900-0959,30.0,615.0,748.0,6.0,762,754.0,-8.0,0.0,0.0,-1.0,1200-1259,0.0,unknown,0.0,237.0,229.0,193.0,1.0,1372.0,6,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999997,2003,4,11,14,5,2003-11-14,US,20355,US,N528AU,1457,10994,1099401,30994,CHS,"Charleston, SC",SC,45.0,South Carolina,37,11057,1105702,31057,CLT,"Charlotte, NC",NC,37.0,North Carolina,36,745,739.0,-6.0,0.0,0.0,-1.0,1200-1259,11.0,750.0,785.0,3.0,799,788.0,-11.0,0.0,0.0,-1.0,1300-1359,0.0,unknown,0.0,54.0,49.0,35.0,1.0,168.0,1,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999998,2012,2,5,15,2,2012-05-15,WN,19393,WN,N281WN,536,13232,1323202,30977,MDW,"Chicago, IL",IL,17.0,Illinois,41,10693,1069302,30693,BNA,"Nashville, TN",TN,47.0,Tennessee,54,1110,1118.0,8.0,8.0,0.0,0.0,1800-1859,8.0,1126.0,1182.0,5.0,1190,1187.0,-3.0,0.0,0.0,-1.0,1900-1959,0.0,unknown,0.0,80.0,69.0,56.0,1.0,395.0,2,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999999,2003,2,4,29,2,2003-04-29,UA,19977,UA,N364UA,1241,12264,1226401,30852,IAD,"Washington, DC",VA,51.0,Virginia,38,13930,1393001,30977,ORD,"Chicago, IL",IL,17.0,Illinois,41,975,970.0,-5.0,0.0,0.0,-1.0,1600-1659,15.0,985.0,1019.0,11.0,1044,1030.0,-14.0,0.0,0.0,-1.0,1700-1759,0.0,unknown,0.0,129.0,120.0,94.0,1.0,589.0,3,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

These early flights will contribute to the 'not delayed' class, therefore we will keep these values in the dataset. It will help the model learn what non-delayed looks like in different instances.

saving cleaned data

In [24]:
df.to_csv("cleaned_flight_data.csv", index=False)